### ISSUE TITLE
httpx.ReadTimeout error

### ISSUE THREAD

**Issue by bjpcjp** [Cito/omnivore-export#2]
I'm new to httpx and could use some assistance. TIA!

File "/home/<mypath>/.local/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

**Comment by Cito** [comment]
The error means that the query timed out. Maybe the server was overloaded, or you queried too much at once.

I now changed the script to query in batches and made the timeout configurable. Let me know if this works for you now.

**Comment by bjpcjp** [comment]
It does. TY!
At first it ran for ~30 secs. I aborted, re-launched & got a results table in ~15 secs. (Total ~12.8K articles & ~1600 tags.)
Appreciate the help.

**Comment by Cito** [comment]
Glad to hear. You can also experiment with increasing the timeout in the script, or selecting a smaller batch size to make the individual requests faster.
