### ISSUE TITLE
Wallabag does not yet support importing from Omnivore

### ISSUE THREAD

**Issue by vaheder** [Cito/omnivore-export#5]
[Per Wallabag](https://wallabag.org/news/20241031-migrate-from-omnivore/) (emphasis mine):

> We understand that this situation may be frustrating and unsettling. We are *actively working* on an Omnivore importer so you can transfer your content to wallabag.

[You mention on the Readme](https://github.com/Cito/omnivore-export/blob/00ded4ef88e7ccd2367e99ea53774d8a8641510d/README.md?plain=1#L30) that as of Wallabag 2.6, one can import Omnivore data. This note sent me on a bit of a tangent setting up an instance and trying to get this working when it is still a work-in-progress and currently unavailable.

While it will work in the future, it is not currently supported as of Wallabag 2.6.9. Please update the Readme to reflect this.

If I am incorrect, please point users to where Wallabag has added support for Omnivore imports.

Thank you for your time and effort putting this script together.

**Comment by Cito** [comment]
You're right, it will be only available in 2.6.10 which is not yet released. But it can be already used in the hosted service. The PR is [here](https://github.com/wallabag/wallabag/pull/7754). I have mentioned this in the README now.

If you want to import it into a self-hosted system, you need to wait for 2.6.10 or install from the current 2.6 branch or use my script. The script should do pretty much the same, it worked very well for me, I have already converted my 2400 links with it.
